Class {
	#name : #GtVmStatisticsReportsNullDiff,
	#superclass : #Object,
	#category : #'GToolkit-Utility-SpaceTally'
}

{ #category : #serialization }
GtVmStatisticsReportsNullDiff class >> leJsonV4Name [

	^ #gtVmStatisticsReportsNullDiff
]

{ #category : #profiling }
GtVmStatisticsReportsNullDiff >> recordSourceReport [
	"Do nothing"
]

{ #category : #profiling }
GtVmStatisticsReportsNullDiff >> recordTargetReport [
	"Do nothing"
]
