Class {
	#name : #GtExtensionMethodsBaseImageOverridesReport,
	#superclass : #Object,
	#instVars : [
		'baseImageExtensionMethodsData'
	],
	#category : #'GToolkit-Utility-ExtensionMethodsAnalysis'
}

{ #category : #accessing }
GtExtensionMethodsBaseImageOverridesReport >> baseImageExtensionMethodsData [
	^ baseImageExtensionMethodsData
]

{ #category : #accessing }
GtExtensionMethodsBaseImageOverridesReport >> baseImageExtensionMethodsData: anObject [
	baseImageExtensionMethodsData := anObject
]
