"
I am a copy of class BaselineOfGToolkitUtility. This comment is copied from there, and might not be entirely accurate

A set of utilities.
"
Class {
	#name : #BaselineOfGToolkitResourcesUtility,
	#superclass : #BaselineOf,
	#category : #BaselineOfGToolkitResourcesUtility
}

{ #category : #baseline }
BaselineOfGToolkitResourcesUtility >> baseline: spec [
	<baseline>
	spec for: #common do: [ 
		spec package: 'GToolkit-Utility-Resources' ]
]
